{
    "cells": [
        {
            "cell_type": "code",
            "execution_count": null,
            "metadata": {},
            "outputs": [],
            "source": [
                "def isDivisible(number):\n",
                "    for i in range(2,21):\n",
                "        if number % i !=0:\n",
                "            return False\n",
                "    return True\n",
                "number=20\n",
                "while True:\n",
                "    if isDivisible(number):\n",
                "        break\n",
                "    number += 20\n",
                "print(number)",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": null,
            "metadata": {},
            "outputs": [],
            "source": [],
        },
        {
            "cell_type": "code",
            "execution_count": null,
            "metadata": {},
            "outputs": [],
            "source": [],
        },
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.7.6",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}
